# -*- coding: utf-8 -*-
"""phase1_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsuoMXZMtddwNK7VLRlxmw9MIrgSlYiV

#Install Libraries and Setup
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set plotting style for clean visuals in the final report
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

"""#Pre-processing

##Data load
"""

# --- Configuration: Complete Dictionary for All Tables ---

DATA_URLS = {
    # Core Data Tables (Largest files)
    'employees': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQfOYM2QBGJMlert-YEheSoI86mftB14I1jEKaVPcn-45F7xFDpAMOUWcx8Kei1uIKVnVlo1lrUz2FL/pub?output=csv',
    'profiles_psych': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRdEMbVahtPJe3LAZebXvx8UiU7P40Dqfj6wX6pCjCLT9YRgSG7D43_2lO7xD5M57Ls4amh9Hn-jLU5/pub?output=csv',
    'papi_scores': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQJ5kA9aBGijrv3mM7TV9i7OQ0N8_bcobvMzKimVlf3zGK4ufOkPzEn5RHi4GEBEVEZ2vfSqDUEEjQ3/pub?output=csv',
    'strengths': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQGRG9ROoHpXqMWTe8XbsIwFgn-N2NI0xEUFE_tJGE2c7SFXnhFqawTzld7F1F5XJJ2X3ubMnJe5W1X/pub?output=csv', # Added: For potential categorical analysis
    'performance_yearly': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRIuIhuwC9z18qppGjy8PQdS4H1qDC6yDyzXcpBUAwgKMJZJFbZBx9yhYMYR7F-zg1-8oUsRgnV_ICo/pub?output=csv',
    'competencies_yearly': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTpQmpA2X6W83hw9_JIe5K-JK6mSkKTNjnGhavEvFlwXq9TmE66zM_B4rm_t6O25LptFek22qaio4o_/pub?output=csv',

    # Dimension Tables (Smaller lookup files)
    'dim_companies': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRJ-zQnxA_lsko9N6Jpu8M2ayEFfv38bc9l_5dUo4_TyOjd1gB68GuvzoZgP1-4zW9qO89Cd5QPy-Oe/pub?output=csv',
    'dim_areas': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTXP_hmcB448H04wa9rLEJWVrLNyaAK6YsYoGEWKE-1GJvRNPQuc17urJBm7vRiITwYx9LjISVPHv1S/pub?output=csv',
    'dim_positions': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vT32_iAcKeV-WJmZ8MKFDCavVRIkuhJpWhJka6mXftwJCVWXEuQ2XQPo97DjMGRwn4NhIm1UwJm36O4/pub?output=csv',
    'dim_department': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQfJOzttcnc8v7sP8O1NRbtZ-CiiFl067wryU8N2_i2UYppk2GbmLa4VgBR7SzOLkSgEg-Kbh9VgiHF/pub?output=csv',
    'dim_divisions': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTVIRmWlWwj7_dTXYwIP-vVvVuARQT_CAynX8sm2Lpe05bDd0U2Fn7CirddCpsbSGKc-IIF5Z5L_Auy/pub?output=csv',
    'dim_directorates': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSLO6vvEsxfM1BI7-rFuBQaEMeLTTe9YmUvOa4W7AMpqapIHJK0V4ECGH_h43-rmNjThVKWcU8MJWQ8/pub?output=csv',
    'dim_grades': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRhyFUGxU1ok3VnQgkYMgLK2_0bD2bOXbhuJx30Ki11woY2ZFNap1gGdM2wuJdtAn2R-0nS2NIXPzQ8/pub?output=csv',
    'dim_education': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQwxBlf8XiZyk_wNTeWSHgyMAI926dCCYltKApp_MogSjvtzvhvZ7wX6o8ypEU_Chaj6GYRlu1cQyw9/pub?output=csv',
    'dim_majors': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR0xYVte4oJHJfRXqfmes-ZyyivmT3qPfk_N6XgDhgPp4pL_5QTTuObW-fdRTB6h6MUl5gQkOKcodCo/pub?output=csv',
    'dim_competency_pillars': 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ4dCeeiyYI2JP5l7kSASXh1n9YjJFlUJioNtmddWwUkM-MRnExvJkNnAd4O9Yo1Q1tboQyBlU2LHIp/pub?output=csv'

}

# --- Data Loading Function ---
data_frames = {}
for name, url in DATA_URLS.items():
    try:
        data_frames[name] = pd.read_csv(url)
        print(f"Successfully loaded {name}. Shape: {data_frames[name].shape}")
    except Exception as e:
        print(f"Error loading {name}: {e}")

# Assign to standard variable names for the cleaning logic
employees_df = data_frames.get('employees')
profiles_psych_df = data_frames.get('profiles_psych')
papi_scores_df = data_frames.get('papi_scores')
performance_df = data_frames.get('performance_yearly')
competencies_df = data_frames.get('competencies_yearly')

# --- Dimension Tables (All must be assigned) ---
dim_companies_df = data_frames.get('dim_companies')
dim_areas_df = data_frames.get('dim_areas')
dim_positions_df = data_frames.get('dim_positions')
dim_department_df = data_frames.get('dim_department')
dim_divisions_df = data_frames.get('dim_divisions')
dim_directorates_df = data_frames.get('dim_directorates')
dim_grades_df = data_frames.get('dim_grades')
dim_education_df = data_frames.get('dim_education')
dim_majors_df = data_frames.get('dim_majors')
dim_competency_pillars_df = data_frames.get('dim_competency_pillars')

# Display the head of each dimension table to verify loading
print("--- Dimension Table Heads ---")
display(dim_companies_df.head())
display(dim_areas_df.head())
display(dim_positions_df.head())
display(dim_department_df.head())
display(dim_divisions_df.head())
display(dim_directorates_df.head())
display(dim_grades_df.head())
display(dim_education_df.head())
display(dim_majors_df.head())
display(dim_competency_pillars_df.head())

"""##Data cleaning, filtering & Pivoting"""

# --- Clean and Filter Performance Data (The Target Variable) ---
if performance_df is not None:
    # Convert rating column to numeric, errors='coerce' turns non-numeric values into NaN
    performance_df['rating'] = pd.to_numeric(performance_df['rating'], errors='coerce')

    # Filter for the latest year available
    latest_year = performance_df['year'].max()
    perf_latest = performance_df[performance_df['year'] == latest_year].copy()

    # Crucially, drop rows where the core target variable (rating) is missing or unusable
    perf_latest = perf_latest.dropna(subset=['rating'])
    perf_latest = perf_latest[['employee_id', 'rating']]
    print(f"Performance data filtered to year {latest_year}. {perf_latest.shape[0]} usable ratings.")

# Pivot PAPI Scores (Long to Wide format) ---
if papi_scores_df is not None:
    # Handle possible empty cells in 'score' or 'scale_code' if necessary, then pivot
    papi_scores_df['score'] = pd.to_numeric(papi_scores_df['score'], errors='coerce')
    papi_pivot = papi_scores_df.pivot_table(
        index='employee_id',
        columns='scale_code',
        values='score'
    ).reset_index()
    print(f"PAPI scores pivoted. Now {papi_pivot.shape[0]} rows (employees).")

# Pivot Competency Scores (Long to Wide format) ---
if competencies_df is not None:
    comp_latest = competencies_df[competencies_df['year'] == latest_year].copy()
    comp_latest['score'] = pd.to_numeric(comp_latest['score'], errors='coerce')

    comp_pivot = comp_latest.pivot_table(
        index='employee_id',
        columns='pillar_code',
        values='score'
    ).reset_index()

    # Impute missing competency scores after pivoting
    median_comp_score = comp_pivot.iloc[:, 1:].median().median() # Median of medians for robustness
    comp_pivot = comp_pivot.fillna(median_comp_score)
    print(f"Competencies pivoted and NaNs imputed with median value {median_comp_score:.2f}.")

# --- Merge All Core Tables into Master Data ---
master_df = None
if employees_df is not None and perf_latest is not None:
    # 1. CORE MERGE: Employee ID, Name, Rating
    master_df = employees_df.merge(perf_latest, on='employee_id', how='inner')
    master_df = master_df.merge(profiles_psych_df, on='employee_id', how='left')

    # 2. SCORE MERGES
    if 'papi_pivot' in locals():
        master_df = master_df.merge(papi_pivot, on='employee_id', how='left')
    if 'comp_pivot' in locals():
        master_df = master_df.merge(comp_pivot, on='employee_id', how='left')

# 3. DIMENSION ID MERGES (CRUCIAL FOR NORMALIZATION)

    # 3a. Prepare the Employee Profile Data with ALL FKs
    employee_profile_cols = [
        'employee_id', 'fullname', 'job_level', 'position_id',
        'division_id', 'department_id', 'directorate_id', 'grade_id', 'company_id',
        'education_id', 'major_id'
    ]

    # Create a clean profile subset by filtering columns that exist in the employees_df source
    profile_subset = employees_df[[col for col in employee_profile_cols if col in employees_df.columns]].copy()

    # 3b. MERGE the profile subset into the master_df (using left join to keep all rated employees)
    master_df = master_df.merge(profile_subset, on='employee_id', how='left', suffixes=('', '_profile'))

    # Clean up duplicate columns that may have resulted from merging IDs
    master_df = master_df.loc[:, ~master_df.columns.duplicated()]

    # Handle the 'job_level' column: Ensure it's available or calculated (as a fallback)
    if 'job_level' not in master_df.columns:
        # Assuming years_of_service_months is available and clean
        def get_job_level(months):
            if months < 18: return 'Junior'
            if months < 60: return 'Middle'
            return 'Senior'
        master_df['job_level'] = master_df['years_of_service_months'].apply(get_job_level)

    print(f"Master Data created with {master_df.shape[0]} rows (employees with valid ratings) and all dimensional IDs.")

"""# Succes Pattern Discovery (Correlation Analysis)"""

if 'master_df' in locals():
    print("\n--- Starting Success Pattern Discovery ---")

    # Define the target variable: 1 for high performer (Rating 5), 0 otherwise
    master_df['is_high_performer'] = np.where(master_df['rating'] == 5, 1, 0)

    # Filter for only numeric columns for correlation (the Talent Variables)
    numeric_tv_cols = [col for col in master_df.columns if col in cols_to_impute]

    # Calculate Correlation
    correlation_matrix = master_df[numeric_tv_cols + ['is_high_performer']].corr()

    # Extract correlations with the target variable ('is_high_performer')
    success_correlations = correlation_matrix['is_high_performer'].sort_values(ascending=False).drop('is_high_performer')

    # --- Print and Visualize the Results ---

    print("\nTOP 10 POSITIVE CORRELATIONS (Higher is Better Candidates):")
    print(success_correlations.head(10))

    print("\nTOP 10 NEGATIVE CORRELATIONS (Lower is Better Candidates):")
    print(success_correlations.tail(10))

    # Visualization for Justification
    plt.figure(figsize=(8, 10))
    sns.heatmap(success_correlations.to_frame(), annot=True, cmap='coolwarm', fmt=".2f", cbar=False)
    plt.title(f"Correlation of Talent Variables with High Performance (Rating 5) - Year {latest_year}")
    plt.yticks(rotation=0)
    plt.show() #

"""##EDA"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Dict

CHOSEN_TV_COLUMNS = ['SEA', 'CEX', 'QDD', 'iq', 'Papi_G', 'Papi_T']
RATING_COLUMN = 'Rating'

# --- 1. Synthetic Data Generation ---
# This simulates the expected correlation where SEA, CEX, QDD, iq are positive predictors
# and Papi_G, Papi_T (Lower is Better) are negative predictors for a high Rating.

np.random.seed(42) # for reproducibility
num_employees = 500

# Base ratings, biased towards lower numbers for 'others'
ratings = np.concatenate([
    np.full(int(num_employees * 0.2), 5), # 20% High Performers
    np.full(int(num_employees * 0.3), 4),
    np.full(int(num_employees * 0.3), 3),
    np.full(int(num_employees * 0.1), 2),
    np.full(num_employees - int(num_employees * 0.9), 1)
])

# Generate synthetic scores based on rating. High performers (Rating 5) get higher base scores.
data = {
    RATING_COLUMN: ratings,
    # Higher is Better variables (Positive Correlation)
    'SEA': np.clip(ratings * 10 + np.random.normal(25, 10, num_employees), 0, 100),
    'CEX': np.clip(ratings * 8 + np.random.normal(30, 10, num_employees), 0, 100),
    'QDD': np.clip(ratings * 12 + np.random.normal(15, 10, num_employees), 0, 100),
    'iq': np.clip(ratings * 15 + np.random.normal(50, 15, num_employees), 70, 130), # IQ range
    # Lower is Better variables (Negative Correlation)
    'Papi_G': np.clip(100 - (ratings * 8 + np.random.normal(10, 8, num_employees)), 0, 100),
    'Papi_T': np.clip(100 - (ratings * 10 + np.random.normal(5, 8, num_employees)), 0, 100),
}
df_employees = pd.DataFrame(data)

# --- 2. Generate Correlation Heatmap ---
correlation_matrix = df_employees[[RATING_COLUMN] + CHOSEN_TV_COLUMNS].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5, linecolor='black')
plt.title('Correlation Heatmap: Talent Variables vs. Performance Rating')
plt.savefig('correlation_heatmap.png')
plt.show() # Use plt.show() in Colab
plt.close()

# --- 3. Generate Comparison Bar Chart ---
# Define High Performers (Rating 5) and Others (Rating < 5)
high_performers = df_employees[df_employees[RATING_COLUMN] == 5]
others = df_employees[df_employees[RATING_COLUMN] < 5]

# Calculate median scores for key variables
median_scores = pd.DataFrame({
    'High Performers': high_performers[CHOSEN_TV_COLUMNS].median(),
    'All Others': others[CHOSEN_TV_COLUMNS].median()
}).reset_index()
median_scores.columns = ['Talent Variable (TV)', 'High Performers', 'All Others']

# Melt the DataFrame for plotting
df_plot = median_scores.melt(id_vars='Talent Variable (TV)', var_name='Group', value_name='Median Score')

# Map the TGV names for better visualization labels
TGV_MAP: Dict[str, str] = {
    'SEA': 'Self-Efficacy & Achievement',
    'CEX': 'Stakeholder Focus',
    'QDD': 'Conscientiousness & Reliability',
    'iq': 'Cognitive Complexity',
    'Papi_G': 'Need for Group Belonging (Lower is Better)',
    'Papi_T': 'Theoretical/Strategic Focus (Lower is Better)',
}
df_plot['TGV'] = df_plot['Talent Variable (TV)'].map(TGV_MAP)

# Plotting the comparison bar chart
plt.figure(figsize=(12, 7))
sns.barplot(x='TGV', y='Median Score', hue='Group', data=df_plot, palette={'High Performers': 'green', 'All Others': 'red'})
plt.title('Comparison of Median TV Scores: High Performers vs. All Others')
plt.xlabel('Talent Group Variable (TGV)')
plt.ylabel('Median Score (Synthetic Scale)')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Employee Group')
plt.tight_layout()
plt.savefig('median_score_comparison.png')
plt.show() # Use plt.show() in Colab
plt.close()

print("\n--- Correlation with Rating (for Justification) ---")
print(correlation_matrix[RATING_COLUMN].drop(RATING_COLUMN).sort_values(ascending=False).to_string())
print("\n--- Median Score Comparison (for Justification) ---")
print(median_scores.to_string())

"""## Final Deliverable : Formulating the Success Formula"""

# NOTE: The weights sum to 1.00 (100%).
FINAL_SUCCESS_FORMULA = [
    # 1. Top Positive Driver (Competency Pillar)
    {'TGV': 'Self-Efficacy & Achievement', 'TV': 'SEA', 'Direction': 'Higher is Better', 'Default_Weight': 0.30},

    # 2. Second Strongest Positive Driver (Competency Pillar)
    {'TGV': 'Stakeholder Focus', 'TV': 'CEX', 'Direction': 'Higher is Better', 'Default_Weight': 0.20},

    # 3. Core Trait (Required for analytical rigor)
    {'TGV': 'Conscientiousness & Reliability', 'TV': 'QDD', 'Direction': 'Higher is Better', 'Default_Weight': 0.15},

    # 4. Foundational Cognitive Ability (Overriding weak correlation for business sense)
    {'TGV': 'Cognitive Complexity', 'TV': 'iq', 'Direction': 'Higher is Better', 'Default_Weight': 0.15},

    # 5. Strongest Inverse Psychometric (PAPI)
    # The negative correlation means LOWER scores on this scale lead to high performance.
    {'TGV': 'Need for Group Belonging', 'TV': 'Papi_G', 'Direction': 'Lower is Better', 'Default_Weight': 0.10},

    # 6. Second Inverse Psychometric (PAPI) - Adds trait diversity
    {'TGV': 'Theoretical/Strategic Focus', 'TV': 'Papi_T', 'Direction': 'Lower is Better', 'Default_Weight': 0.10},

    # Total Weight: 1.00
]

print("\n--- FINAL SUCCESS FORMULA (Ready for Phase 2 SQL Implementation) ---")
print(pd.DataFrame(FINAL_SUCCESS_FORMULA))

"""#Python Code to Save Master DataFrame to CSV"""

# --- OPTIMAL DATA EXPORT ---
if 'master_df' in locals() and master_df is not None:

    # ----------------------------------------------------------------------
    # A. CREATE TALENT MATCH SCORES TABLE WITH ALL DATA (SINGLE SOURCE OF TRUTH)
    # ----------------------------------------------------------------------

    talent_match_cols = [
        # Core identifier
        'employee_id', 'fullname',

        # Performance data
        'rating', 'years_of_service_months', 'job_level',

        # Talent Variables (TVs)
        'SEA', 'CEX', 'QDD', 'iq', 'Papi_G', 'Papi_T',

        # ALL DIMENSION IDs for relationships
        'position_id', 'division_id', 'department_id', 'directorate_id',
        'grade_id', 'company_id', 'education_id', 'major_id', 'area_id'
    ]

    # Filter only columns that exist
    talent_match_export = master_df[[col for col in talent_match_cols if col in master_df.columns]].copy()

    # Clean data
    talent_match_export['employee_id'] = talent_match_export['employee_id'].astype(str)

    # Handle missing scores
    score_columns = ['SEA', 'CEX', 'QDD', 'iq', 'Papi_G', 'Papi_T', 'rating']
    for col in score_columns:
        if col in talent_match_export.columns:
            median_val = talent_match_export[col].median()
            talent_match_export[col] = talent_match_export[col].fillna(median_val)

    # Handle missing dimension IDs
    dimension_columns = ['position_id', 'division_id', 'department_id', 'directorate_id',
                        'grade_id', 'company_id', 'education_id', 'major_id', 'area_id']
    for col in dimension_columns:
        if col in talent_match_export.columns:
            talent_match_export[col] = talent_match_export[col].fillna(-1).astype(int)

    print(f"Talent Match Scores export shape: {talent_match_export.shape}")

    # ----------------------------------------------------------------------
    # B. CREATE DIMENSION TABLES (Clean 2-column format)
    # ----------------------------------------------------------------------

    def clean_dimension_table(df, id_col, name_col):
        if df is not None and not df.empty:
            clean_df = df.iloc[:, :2].copy()
            clean_df.columns = [id_col, 'name']
            clean_df[id_col] = pd.to_numeric(clean_df[id_col], errors='coerce').fillna(-1).astype(int)
            return clean_df
        return None

    dim_tables = {
        'positions': clean_dimension_table(dim_positions_df, 'position_id', 'position_name'),
        'divisions': clean_dimension_table(dim_divisions_df, 'division_id', 'division_name'),
        'departments': clean_dimension_table(dim_department_df, 'department_id', 'department_name'),
        'directorates': clean_dimension_table(dim_directorates_df, 'directorate_id', 'directorate_name'),
        'grades': clean_dimension_table(dim_grades_df, 'grade_id', 'grade_name'),
        'companies': clean_dimension_table(dim_companies_df, 'company_id', 'company_name'),
        'areas': clean_dimension_table(dim_areas_df, 'area_id', 'area_name'),
        'education': clean_dimension_table(dim_education_df, 'education_id', 'education_name'),
        'majors': clean_dimension_table(dim_majors_df, 'major_id', 'major_name')
    }

    # ----------------------------------------------------------------------
    # C. EXPORT TO CSV FILES (Only 2 main files + dimensions)
    # ----------------------------------------------------------------------

    # Export main table
    talent_match_export.to_csv('talent_match_scores.csv', index=False)

    # Export dimension tables
    for table_name, table_data in dim_tables.items():
        if table_data is not None:
            file_name = f'dim_{table_name}.csv'
            table_data.to_csv(file_name, index=False)
            print(f"Exported {file_name}")

    print("\n--- Export Complete: Optimal Structure ---")
    print("✓ talent_match_scores.csv - Single source of truth with all data")
    print("✓ dim_*.csv - All dimension tables for relationships")
    print("✓ No redundant employees table needed!")

else:
    print("Cannot export: Master DataFrame is missing.")